spring:
  application:
    name: bbeaulife

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: todak
    password: todak
    driver-class-name: org.postgresql.Driver

  #  flyway:
  #    enabled: true
  #    baseline-version: 0
  #    baseline-on-migrate: true
  #    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
