CREATE TABLE ACCOUNT
(
    ACCOUNT_ID         BIGINT PRIMARY KEY,
    EMAIL              VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD           VARCHAR(255) NOT NULL UNIQUE,
    ENROLLED_DATE_TIME TIMESTAMP    NOT NULL,
    UPDATED_DATE_TIME  TIMESTAMP    NOT NULL
)